version: 0.2

phases:
  install:
    commands:
      # Install CDK
      - npm install -g npm@6.4.1 aws-cdk@0.18.1

  build:
    commands:
      # Set up environment variables
      - AWS_ACCOUNT_ID=`echo $CODEBUILD_BUILD_ARN | awk -F":" '{print $5}'`
      - ECR_REPO=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - $(aws ecr get-login --no-include-email)
      # Build Docker image
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ECR_REPO:$IMAGE_TAG
      - docker push $ECR_REPO:$IMAGE_TAG
      # Synthesize CloudFormation templates
      - cd cdk
      - npm ci
      - npm run build
      - cdk synth --app 'node ecs-service.js' > ../template.yml

artifacts:
  files:
    - template.yml
